export const issues = [
  {
    id: "issue-1",
    repo: "facebook/react",
    title: "Refactor Context Provider Logic",
    description:
      "Overview We are looking to streamline the context provider internal state management to prevent unnecessary re-renders in heavy DOM trees. Problem Statement...",
    difficulty: "Easy",
    language: "TypeScript",
    time: "2h ago",
    comments: 12,
    stars: "204k",
    icon: "terminal",
    saved: true,
  },
  {
    id: "issue-2",
    repo: "supabase/postgrest",
    title: "Optimize filter performance for large tables",
    description:
      "Background Current SQL generation in certain nested query filters leads to inefficient sequential scans on partitions with more than 1M rows. The Situation...",
    difficulty: "Hard",
    language: "Haskell",
    time: "5h ago",
    comments: 31,
    stars: "25k",
    icon: "database",
    saved: false,
  },
  {
    id: "issue-3",
    repo: "vercel/next.js",
    title: "Support for new Edge Runtime features",
    description:
      "Explanation Surface the newest runtime capabilities through the route compiler and document safe usage for application routes...",
    difficulty: "Medium",
    language: "TypeScript",
    time: "1d ago",
    comments: 24,
    stars: "112k",
    icon: "terminal",
    saved: false,
  },
  {
    id: "issue-4",
    repo: "trpc/trpc",
    title: "Fix circular dependency in inference",
    description:
      "Issue description Deep type inference can loop when routers import shared helper contracts from generated client files...",
    difficulty: "Hard",
    language: "TypeScript",
    time: "3d ago",
    comments: 5,
    stars: "32k",
    icon: "activity",
    saved: true,
  },
  {
    id: "issue-5",
    repo: "tailwindlabs/tailwindcss",
    title: "Implement container query support for dynamic grid layouts",
    description:
      "Feature Proposal We need to add native support for @container queries to complement the existing @media viewport-query system. This will allow highly reusable...",
    difficulty: "Medium",
    language: "TypeScript",
    time: "2 days ago",
    comments: 14,
    stars: "74.2k",
    icon: "terminal",
    saved: false,
  },
  {
    id: "issue-6",
    repo: "prisma/prisma",
    title: "Optimize SQL Query Performance",
    description:
      "Issue details The Prisma Query Engine emits redundant SELECT operations when constructing deep nested relationship queries. Goals - Implement automated dynam...",
    difficulty: "Medium",
    language: "TypeScript",
    time: "1w ago",
    comments: 19,
    stars: "38k",
    icon: "database",
    saved: false,
  },
  {
    id: "issue-7",
    repo: "nodejs/node",
    title: "Race condition in WebWorker threads",
    description:
      "Thread Synchronization Bug A rare but blocking race condition occurs in Node's Worker Threads lifecycle when tearing down asynchronous thread communication str...",
    difficulty: "Hard",
    language: "TypeScript",
    time: "4d ago",
    comments: 43,
    stars: "105k",
    icon: "terminal",
    saved: false,
  },
  {
    id: "issue-8",
    repo: "excalidraw/excalidraw",
    title: "Add support for SVG exports in drawing pipeline",
    description:
      "Feature Request Enable drawing boards to export svg nodes fully containing vector stylesheets and local typography rules. This preserves consistent layout rend...",
    difficulty: "Easy",
    language: "TypeScript",
    time: "10h ago",
    comments: 7,
    stars: "45k",
    icon: "activity",
    saved: false,
  },
];

export const stacks = ["All", "TypeScript", "JavaScript", "Python", "Rust", "Haskell"];

export const difficulties = ["All", "Easy", "Medium", "Hard"];

export const tags = [
  "All",
  "backend",
  "bug",
  "core",
  "edge",
  "enhancement",
  "feature",
  "good first issue",
  "performance",
  "refactor",
  "runtime",
  "sql",
  "ui/ux",
  "v4.0-alpha",
];
